[build]
builder = "nixpacks"

[build.buildCommand]
value = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "always"

[variables]
NODE_ENV = "production"